### ISSUE TITLE
Choose a better method name prefix than `as_`

### ISSUE THREAD

**Issue by mystor** [mystor/literalext#2]
As mentioned in https://github.com/dtolnay/syn/issues/153#issuecomment-308135180 the `as_` prefix makes it sound like these conversions are cheap, when they definitely are not. We should consider using a different prefix.

`to_` would work well, but if we do that we'll need a different method name than `to_string` as it conflicts with `Literal`'s `Display` implementation.

cc @alexcrichton

**Comment by alexcrichton** [comment]
Maybe `parse_*` as that's what's happening under the hood?

**Comment by mystor** [comment]
Fixed in 81d85f013e918407247491ac4c7661e2f7348097
