### ISSUE TITLE
Actually test the `proc_macro` integration

### ISSUE THREAD

**Issue by mystor** [mystor/literalext#3]
This crate was written before the new `proc_macro` API had landed in nightly. We should confirm that it actually works correctly with that API.

**Comment by mystor** [comment]
A nightly hasn't been cut yet with https://github.com/rust-lang/rust/pull/40939 in it. I'm going to hold off on publishing to crates.io until I can test that this crate's `proc_macro` feature compiles unless someone needs it before then.

**Comment by lambda-fairy** [comment]
I've been using it with `proc_macro` in [Maud](https://github.com/lfairy/maud/compare/proc-macro), and can confirm that it compiles under nightly (086eaa78e 2017-07-15).

(Note that the failing tests there are because of missing pieces in my own code, not issues with literalext)

**Comment by mystor** [comment]
Fixed by #4
